[package]
name = "dedup"
version = "0.1.0"
authors = ["asui <k.sickeler@gmail.com>"]

[dependencies]
clap = "*"
filehash = { git = "https://github.com/asuivelentine/filehash", branch = "master" }
quick-error = "*"
